- be/applications/alert-application/src/main/java/com/pda/alertapplication/controller/AlertController.java
- be/applications/alert-application/src/main/java/com/pda/alertapplication/repository/EmitterRepository.java
- be/applications/alert-application/src/main/java/com/pda/alertapplication/service/AlertMessage.java
- be/applications/alert-application/src/main/java/com/pda/alertapplication/service/EmitterService.java
- be/applications/membership-application/src/main/java/com/pda/membershipapplication/controller/MembershipController.java
- be/applications/membership-application/src/main/java/com/pda/membershipapplication/service/MembershipService.java
- be/applications/membership-application/src/main/java/com/pda/membershipapplication/service/dto/res/MyMembershipServiceResponse.java
- conf/nginx.conf
> feat: alert

- conf/grafana.ini
- conf/prometheus.yml
> feat: monitoring

- conf/nginx.conf
- docker-compose.yml
- fe/conf/default.conf
- 포트 변경 및, gitignore env 추가
<br/>
-
<br/>
-
<br>
> fix: fix fe port

- conf/nginx.conf
- docker-compose.yml
- fe/Dockerfile
- fe/conf/default.conf
> fix: Fe port

- be/applications/ets-application/src/main/java/com/pda/etsapplication/api/WebClientAPI.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/controller/EtsController.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/service/EtsService.java
- be/applications/ets-application/src/main/resources/application.yml
- docker-compose.yml
- hotfix ets-server
<br/>
-
<br/>
-
<br>
> fix: enviroment ets-server

- fe/src/components/detail/ChartContainer.jsx
> delete: 불필요한 코드 삭제

- be/applications/ets-application/src/main/java/com/pda/etsapplication/controller/dto/res/StocksDto.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/service/EtsService.java
> refactor: get stockcode

- be/applications/ets-application/src/main/java/com/pda/etsapplication/controller/EtsController.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/repository/DescriptionEntity.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/repository/DescriptionRepository.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/service/EtsService.java
- be/applications/ets-application/src/main/resources/application.yml
> feat: ets description

- be/applications/account-application/src/main/java/com/pda/accountapplication/controller/AccountController.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/dto/SellQuantityDto.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/repository/HoldingRepository.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/service/HoldingService.java
> feat: add get sell quantity api

- be/applications/account-application/src/main/java/com/pda/accountapplication/controller/AccountController.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/service/AccountService.java
> hotfix: 계좌조회

- be/applications/account-application/src/main/java/com/pda/accountapplication/controller/AccountController.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/service/AccountService.java
> feat: 토탈 조회

- be/applications/account-application/src/main/java/com/pda/accountapplication/repository/HoldingRepository.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/service/HoldingService.java
> feat: update get sell quantity (null error)

- be/applications/account-application/src/main/java/com/pda/accountapplication/controller/AccountController.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/dto/PutHoldingDto.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/repository/Account.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/repository/AccountRepository.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/repository/Holding.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/service/HoldingService.java
- be/applications/ets-application/build.gradle
- be/applications/ets-application/src/main/java/com/pda/etsapplication/api/WebClientAPI.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/config/KafkaProducerConfig.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/controller/EtsController.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/dto/PutHoldingDto.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/service/EtsService.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/service/OfferService.java
- be/applications/ets-application/src/main/resources/application.yml
- be/utils/kafka-util/src/main/java/com/pda/kafkautil/TradeKafkaDto.java
> feat: 매수/매도

- be/applications/account-application/src/main/java/com/pda/accountapplication/controller/TestKafkaController.java
- be/applications/account-application/src/main/java/com/pda/accountapplication/service/HoldingService.java
> hotfix: holding else null

- be/applications/account-application/src/main/java/com/pda/accountapplication/service/HoldingService.java
> hotfix: holdinglog

- conf/nginx.conf
> hotfix: conf

- be/applications/account-application/src/main/java/com/pda/accountapplication/service/HoldingService.java
> hotfix: selling

- be/applications/account-application/src/main/java/com/pda/accountapplication/service/HoldingService.java
- be/applications/ets-application/src/main/java/com/pda/etsapplication/service/OfferService.java
> feat:putholding log

- fe/src/routes/MainPage.jsx
> fix: 메인페이지 MY거래에서 NaN뜨던 버그 수정

- fe/src/routes/MainPage.jsx
> fix: 몇주 보유했는지 확인가능
